# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib SAGMM
NULL

#'Mahalanobis Distance
#'@description THIS FUNCTION DOES
#'@param PARAM1
#'@param PARAM2
#'@return RETURNVAL
#'@examples
#'@export
mahalanobis_HD <- function(y, mu, sigma) {
    .Call('_SAGMM_mahalanobis_HD', PACKAGE = 'SAGMM', y, mu, sigma)
}

#'Euclidean Distance
#'@description THIS FUNCTION DOES
#'@param PARAM1
#'@param PARAM2
#'@return RETURNVAL
#'@examples
#'@export
norm_HD <- function(y, mu, sigma) {
    .Call('_SAGMM_norm_HD', PACKAGE = 'SAGMM', y, mu, sigma)
}

#'Main Computation Loop
#'@description THIS FUNCTION DOES
#'@param PARAM1
#'@param PARAM2
#'@return RETURNVAL
#'@examples
#'@export
main_loop <- function(Number, Groups, PISTAR_O, MU_O, LAMBDA_O, GAMMA, X, Dimensions, SIGMA) {
    .Call('_SAGMM_main_loop', PACKAGE = 'SAGMM', Number, Groups, PISTAR_O, MU_O, LAMBDA_O, GAMMA, X, Dimensions, SIGMA)
}

